models:
  gpt2-small:
    default_text: "The quick brown fox jumps over the lazy dog."
    description: "GPT-2 Small model with 117M parameters"
    max_length: 1024
  pythia-2.8b:
    default_text: "In the beginning, there was light."
    description: "Pythia 2.8B model"
    max_length: 2048

visualization:
  graph:
    default_width: 1000
    default_height: 700
    edge_opacity: 0.6
    node_size: 8
    font_size: 12
  theme:
    background: "#FFFFFF"
    primary: "#3B82F6"
    secondary: "#10B981"
    text: "#1F2937"
    text_light: "#6B7280"
    border: "#E5E7EB"
    error: "#EF4444"
    success: "#10B981"
    warning: "#F59E0B"

api:
  base_url: "http://localhost:8000"
  timeout: 30
  health_check_timeout: 10 